-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'a999f5b6bc30a97c' HASH '05eb6e3ef3aa7a8a25fbce8b3dc775da5af17ca41110f2875cf9016d6086c81b' ADMIN;         
CREATE SEQUENCE "PUBLIC"."CUSTOMER_SEQ" START WITH 104 INCREMENT BY 1;         
CREATE SEQUENCE "PUBLIC"."CUSTOMER_TRANSACTION_SEQ" START WITH 11 INCREMENT BY 1;             
CREATE SEQUENCE "PUBLIC"."REWARD_POINTS_SEQ" START WITH 11 INCREMENT BY 1;    
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_CUSTOMER"(
    "CREATED_BY" INTEGER,
    "ID" INTEGER,
    "MODIFIED_BY" INTEGER,
    "RN_" INTEGER NOT NULL,
    "STATUS" BOOLEAN,
    "CREATED_DATE" TIMESTAMP(6),
    "MODIFIED_DATE" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "MOBILE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."HTE_CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_CUSTOMER;            
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_REWARD_POINTS"(
    "CUSTOMER_ID" INTEGER,
    "DATE" DATE,
    "ID" INTEGER,
    "POINTS" INTEGER,
    "REWARD_MONTH" INTEGER,
    "REWARD_YEAR" INTEGER,
    "RN_" INTEGER NOT NULL
);  
ALTER TABLE "PUBLIC"."HTE_REWARD_POINTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("RN_");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_REWARD_POINTS;       
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_CUSTOMER_TRANSACTION"(
    "CUSTOMER_ID" INTEGER,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "AMOUNT" FLOAT(53),
    "DATE" TIMESTAMP(6),
    "SPENT_DETAILS" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."HTE_CUSTOMER_TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_CUSTOMER_TRANSACTION;
CREATE MEMORY TABLE "PUBLIC"."CUSTOMER"(
    "ID" INTEGER NOT NULL,
    "CREATED_BY" INTEGER NOT NULL,
    "CREATED_DATE" TIMESTAMP(6) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "MOBILE" CHARACTER VARYING(255),
    "MODIFIED_BY" INTEGER,
    "MODIFIED_DATE" TIMESTAMP(6),
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "STATUS" BOOLEAN NOT NULL
); 
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;
CREATE MEMORY TABLE "PUBLIC"."CUSTOMER_TRANSACTION"(
    "ID" INTEGER NOT NULL,
    "AMOUNT" FLOAT(53) NOT NULL,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "DATE" TIMESTAMP(6) NOT NULL,
    "SPENT_DETAILS" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."CUSTOMER_TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_TRANSACTION;    
CREATE MEMORY TABLE "PUBLIC"."REWARD_POINTS"(
    "ID" INTEGER NOT NULL,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "POINTS" INTEGER NOT NULL,
    "REWARD_MONTH" INTEGER NOT NULL,
    "REWARD_YEAR" INTEGER NOT NULL
);       
ALTER TABLE "PUBLIC"."REWARD_POINTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5D" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REWARD_POINTS;  

